# Generated by Django 3.0.5 on 2024-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('b_form_id', models.CharField(max_length=20)),
                ('father_id_card', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('section', models.CharField(choices=[('Abu Baker', 'Abu Baker'), ('Umer', 'Umer'), ('Usman', 'Usman'), ('Ali', 'Ali')], max_length=20)),
                ('student_class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('dob', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='student_pictures/')),
                ('address', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
